name: Feature Branch CI

on:
  push:
    branches:
      - "feature/*"

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven+
        run: mvn -B test --file pom.xml

        #git add.
        #git commit -m 'add'
        #git push